### ISSUE TITLE
support mechanism of validating the content hashes of binaries

### ISSUE THREAD

**Issue by tmc** [marwanhawari/stew#1] opened 2022-02-01 04:56 UTC
Great tool! Adding the ability for content hashes to be collected would be a great step to help ensure supply chains remain unaltered.

Perhaps extend your Stewfile to include a sha256 of the binary? you may want to consider some sort of registry to help prevent tampering (for example, newly installed binaries could trigger some automation to collect and save sha information into something you could look up against).

**Comment by marwanhawari** [comment] 2022-02-05 04:19
Thanks for the feedback! Yeah I've been considering how to incorporate hashes, but I'm a little hesitant to start maintaining any sort of central registry because I feel it's antithetical to this project's goal.

I think extending the `Stewfile` to include hashes could work though. Perhaps if you install from a `Stewfile` that has hashes, then `stew` will verify the hash of the downloaded asset before installing the binary. Or maybe verify the hash of the binary itself? Not sure what approach is better. This probably involves keeping track of hashes in the `Oakfile.lock.json` and making a new `--hashes` flag for `stew list` so you could do something like 
```
stew list --hashes > Stewfile
```
Definitely possible.

**Comment by cardil** [comment] 2023-02-27 17:17
I think the stew could have support for validating checksums projects often publish.

I see 2 patterns people use:

### one `checksums.txt` file

The most often used pattern, where the `checksums.txt` file contains sha256 hashes. It could be verified with:

```shell
$ sha256sum --check --ignore-missing checksums.txt
```

Example: https://github.com/knative/client/releases/tag/knative-v1.9.0

### Multiple `<artifact>.sha256` file

The other pattern is to host `.sha256` for each of the hosted artifacts. It could be verified with:

```shell
$ [ "$(sha256sum minikube-linux-amd64 | awk '{print $1}')" = "$(cat minikube-linux-amd64.sha256)" ]
```

Example: https://github.com/kubernetes/minikube/releases/tag/v1.29.0

**Comment by marwanhawari** [comment] 2024-04-07 07:50
This is addressed by the new ability to have reproducible batch installs from the Stewfile.lock.json (https://github.com/marwanhawari/stew/pull/15, https://github.com/marwanhawari/stew/pull/35, https://github.com/marwanhawari/stew/pull/42, https://github.com/marwanhawari/stew/pull/43). This was a part of the [v0.4.0 release](https://github.com/marwanhawari/stew/releases/tag/v0.4.0).

**Closed by marwanhawari** 2024-04-07 07:50 UTC
